name: comment test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  pull-requests: write
## aaa
jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest
#    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout2
        uses: marocchino/sticky-pull-request-comment@v2
        with:
         header: <same-header-as-the-step-that-added-the-comment>
         hide: true
         hide_classify: "OUTDATED"
         message: |
          Release 111
          eeeeeeasfda
          sdafasffahjdfkjs
          dsafhjasdhfajkd
